const DKEY='my_duaa_items_v1',SKEY='my_duaa_settings_v1';
const defaults={theme:'light',showTitles:true,fontSize:24,lineHeight:1.8,weight:'500',radius:28,padX:22,padY:24,gap:14};
const seed=[{id:uid(),title:'دعاء طلب الرزق',text:'اللهم ارزقني رزقًا حلالًا طيبًا، وبارك لي فيه، واكفني بفضلك عمّن سواك.',ref:'',icon:'leaf'},{id:uid(),title:'دعاء الطمأنينة',text:'اللهم اطمئن قلبي، وأزل عني كل هم وحزن، واجعلني في كنفك ورعايتك دائمًا.',ref:'',icon:'heart'},{id:uid(),title:'دعاء المغفرة',text:'رب اغفر لي ذنوبي كلها، دقها وجلها، أولها وآخرها، وما علمت منها وما لم أعلم.',ref:'',icon:'dome'}];
let duas=load(DKEY,seed);duas=duas.map((d,i)=>({id:d.id||uid(),title:d.title||'',text:d.text||'',ref:d.ref||'',icon:d.icon||['leaf','heart','dome'][i%3]}));
let old=load(SKEY,{});let settings={...defaults,...old,theme:old.theme==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):(old.theme||'light'),showTitles:old.showTitles??true,fontSize:old.fontSize??old.size??24,lineHeight:old.lineHeight??old.line??1.8,weight:String(old.weight??'500'),radius:old.radius??28,padX:old.padX??old.padding??22,padY:old.padY??old.padding??24,gap:old.gap??14};
let editingId=null,actionId=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function load(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}}
function persist(){localStorage.setItem(DKEY,JSON.stringify(duas))}
function persistSettings(){localStorage.setItem(SKEY,JSON.stringify(settings))}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function badge(t){if(t==='heart')return '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 21s-7-4.5-7-10a4 4 0 0 1 7-2.4A4 4 0 0 1 19 11c0 5.5-7 10-7 10Z"/></svg>';if(t==='dome')return '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M4 19h16v2H4zM6 18v-5.5c0-3.3 2.3-5.7 5-6.3V4.7a1 1 0 1 1 2 0v1.5c2.7.6 5 3 5 6.3V18H6Z"/></svg>';return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 14c0-5 4-8 11-8 0 7-3 11-8 11-2 0-3-.7-3-3Z"/><path d="M7 17c1-3 4-6 8-8"/></svg>'}
const copySvg='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="9" y="7" width="11" height="13" rx="2"/><path d="M5 16H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>';
function apply(){const r=document.documentElement;r.dataset.theme=settings.theme;r.classList.toggle('titles-off',!settings.showTitles);r.style.setProperty('--fs',settings.fontSize+'px');r.style.setProperty('--lh',settings.lineHeight);r.style.setProperty('--fw',settings.weight);r.style.setProperty('--radius',settings.radius+'px');r.style.setProperty('--px',settings.padX+'px');r.style.setProperty('--py',settings.padY+'px');r.style.setProperty('--gap',settings.gap+'px');$('#themeColor').content=settings.theme==='dark'?'#0f1619':'#f6f1e9';sync();render()}
function render(){const n=duas.length;$('#count').textContent=n===1?'دعاء واحد':n+' أدعية';$('#list').innerHTML=duas.map((d,i)=>`<article class="card" data-id="${d.id}"><div class="card-head"><div class="title-wrap">${d.title?`<div class="card-badge">${badge(d.icon)}</div><div class="card-title">${esc(d.title)}</div>`:''}</div><button class="menu" data-action="menu" aria-label="خيارات الدعاء">…</button></div><p class="dua">${esc(d.text)}</p>${d.ref?`<div class="ref">${esc(d.ref)}</div>`:''}<div class="card-actions"><button class="action" data-action="copy" aria-label="نسخ الدعاء">${copySvg}</button></div></article>`).join('');$$('.card[data-id]').forEach(c=>c.onclick=async e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;e.stopPropagation();const id=c.dataset.id;if(a==='copy'){const d=duas.find(x=>x.id===id);try{await navigator.clipboard.writeText((settings.showTitles&&d.title?d.title+'\n':'')+d.text)}catch{}toast('تم النسخ')}else if(a==='menu')openActions(id)});renderPreview()}
function renderPreview(){const p=$('#preview');if(!p)return;p.innerHTML=`<article class="card"><div class="card-head"><div class="title-wrap"><div class="card-badge">${badge('leaf')}</div><div class="card-title">دعاء طلب الرزق</div></div><button class="menu">…</button></div><p class="dua">اللهم ارزقني رزقًا حلالًا طيبًا، وبارك لي فيه، واكفني بفضلك عمّن سواك.</p><div class="card-actions"><button class="action">${copySvg}</button></div></article>`}
function sync(){if(!$('#titleSwitch'))return;$('#titleSwitch').classList.toggle('on',settings.showTitles);[['fontRange','fontVal',settings.fontSize,'px'],['lineRange','lineVal',settings.lineHeight,''],['radiusRange','radiusVal',settings.radius,'px'],['padXRange','padXVal',settings.padX,'px'],['padYRange','padYVal',settings.padY,'px'],['gapRange','gapVal',settings.gap,'px']].forEach(([a,b,v,s])=>{const el=$('#'+a);if(el)el.value=v;const out=$('#'+b);if(out)out.textContent=(a==='lineRange'?Number(v).toFixed(2):v)+s});$$('#themeSeg .seg').forEach(x=>x.classList.toggle('active',x.dataset.value===settings.theme));$$('#weightSeg .seg').forEach(x=>x.classList.toggle('active',x.dataset.value===String(settings.weight)));renderPreview()}
function set(k,v){settings[k]=v;persistSettings();apply()}
function openEditor(id=null){editingId=id;const d=id?duas.find(x=>x.id===id):null;$('#editorTitle').textContent=d?'تعديل الدعاء':'إضافة دعاء';$('#titleInput').value=d?.title||'';$('#duaInput').value=d?.text||'';$('#refInput').value=d?.ref||'';$('#editorOverlay').classList.add('show');setTimeout(()=>$('#duaInput').focus(),80)}
function closeEditor(){editingId=null;$('#editorOverlay').classList.remove('show')}
function saveEditor(){const text=$('#duaInput').value.trim();if(!text)return;const data={title:$('#titleInput').value.trim(),text,ref:$('#refInput').value.trim()};if(editingId){const d=duas.find(x=>x.id===editingId);Object.assign(d,data)}else duas.push({id:uid(),icon:['leaf','heart','dome'][duas.length%3],...data});persist();closeEditor();render()}
function openActions(id){actionId=id;$('#actionOverlay').classList.add('show')}
function closeActions(){actionId=null;$('#actionOverlay').classList.remove('show')}
function move(dir){const i=duas.findIndex(x=>x.id===actionId),j=i+dir;if(i<0||j<0||j>=duas.length)return;[duas[i],duas[j]]=[duas[j],duas[i]];persist();closeActions();render()}
function del(){duas=duas.filter(x=>x.id!==actionId);persist();closeActions();render()}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>x.classList.remove('show'),1100)}
$('#addBtn').onclick=$('#quickAddBtn').onclick=()=>openEditor();
$('#settingsBtn').onclick=()=>{$('#settingsOverlay').classList.add('show');sync()};
$('#closeEditor').onclick=$('#cancelEditor').onclick=closeEditor;$('#saveBtn').onclick=saveEditor;
$('#closeSettings').onclick=()=>$('#settingsOverlay').classList.remove('show');$('#resetBtn').onclick=()=>{settings={...defaults};persistSettings();apply()};
$('#titleSwitch').onclick=()=>set('showTitles',!settings.showTitles);
[['fontRange','fontSize'],['lineRange','lineHeight'],['radiusRange','radius'],['padXRange','padX'],['padYRange','padY'],['gapRange','gap']].forEach(([id,k])=>$('#'+id).oninput=e=>set(k,+e.target.value));
$$('#themeSeg .seg').forEach(x=>x.onclick=()=>set('theme',x.dataset.value));$$('#weightSeg .seg').forEach(x=>x.onclick=()=>set('weight',x.dataset.value));
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===t));$$('.panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===t.dataset.tab))});
$('#actionEdit').onclick=()=>{const id=actionId;closeActions();openEditor(id)};$('#actionUp').onclick=()=>move(-1);$('#actionDown').onclick=()=>move(1);$('#actionDelete').onclick=del;$('#actionClose').onclick=closeActions;
[['editorOverlay',closeEditor],['settingsOverlay',()=>$('#settingsOverlay').classList.remove('show')],['actionOverlay',closeActions]].forEach(([id,fn])=>$('#'+id).onclick=e=>{if(e.target.id===id)fn()});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));apply();